# Generated by Django 5.2.5 on 2025-08-15 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('has_cover', models.BooleanField(default=False)),
                ('has_model', models.BooleanField(default=False)),
                ('has_pages', models.BooleanField(default=False)),
                ('cover_image', models.URLField(blank=True, help_text='Deprecated: Use S3 storage')),
                ('gltf_url', models.URLField(blank=True, help_text='Deprecated: Use S3 storage')),
                ('sample_pdf_url', models.URLField(blank=True, help_text='Deprecated: Use S3 storage')),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.author')),
                ('genres', models.ManyToManyField(blank=True, to='catalog.genre')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', 'created_at'], name='catalog_boo_author__1c654d_idx'), models.Index(fields=['available_copies'], name='catalog_boo_availab_c08bdd_idx')],
            },
        ),
    ]
